### ISSUE TITLE
timeout on `SocketInputStream#socketRead0` during SOAP request

### ISSUE THREAD

**Issue by aaronblenkush** [avadev/AvaTax-Calc-SOAP-java#3]
Is anybody else experiencing issues with the SOAP API since about 2015-09-10 01:00:00 PDT? Avalara insist that their services are functioning normally, although there are "several reports of issues which appear to be ISP related". Their GitHub examples for [AvaTax-Calc-REST-cURL](https://github.com/avadev/AvaTax-Calc-REST-cURL) and [AvaTax-Calc-REST-java](https://github.com/avadev/AvaTax-Calc-REST-java) work fine on my machine, but this example [AvaTax-Calc-SOAP-java](https://github.com/avadev/AvaTax-Calc-SOAP-java) does **not**.

Packet captures show that the usual SSH ceremony completes, but there is no response after the client sends the body of the HTTP request (the SOAP message). The JVM is clearly hanging on reading from the `SocketInputStream`.

    "main@1" prio=5 tid=0x1 nid=NA runnable
      java.lang.Thread.State: RUNNABLE
	      at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	      at java.net.SocketInputStream.read(SocketInputStream.java:152)
	      at java.net.SocketInputStream.read(SocketInputStream.java:122)
	      at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	      at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	      at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	      - locked <0x776> (a java.lang.Object)
	      at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
	      at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	      - locked <0x763> (a sun.security.ssl.AppInputStream)
	      at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	      at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	      - locked <0x764> (a java.io.BufferedInputStream)
	      at org.apache.axis.transport.http.HTTPSender.readHeadersFromSocket(HTTPSender.java:583)
	      at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:143)
	      at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	      at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	      at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	      at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
	      at org.apache.axis.client.Call.invokeEngine(Call.java:2765)
	      at org.apache.axis.client.Call.invoke(Call.java:2748)
	      at org.apache.axis.client.Call.invoke(Call.java:2424)
	      at org.apache.axis.client.Call.invoke(Call.java:2347)
	      at org.apache.axis.client.Call.invoke(Call.java:1804)
	      at com.avalara.avatax.services.base.BaseSvcSoapStub.invokeService(BaseSvcSoapStub.java:190)
	      at com.avalara.avatax.services.tax.TaxSvcSoapStub.getTax(TaxSvcSoapStub.java:579)
	      at GetTaxTest.main(GetTaxTest.java:198)

**Comment by aaronblenkush** [comment]
No explanation as to the cause, but it is working now.
